config/routes.rb
Rails.application.routes.draw do
  
  get 'static/index'
  get 'static/dashboard'
  devise_for :users
  resources  :parties
  resources  :rsvps
  root 'static#index'
  match ':controller(/:action(/:id))', :via => :get

end

app/models/party.rb
class Party < ActiveRecord::Base
  belongs_to  :user
  has_many    :rsvps
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :user
  belongs_to :party
  validates :user_id, :uniqueness => { :scope => :party_id }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :parties
  has_many :rsvps
  def owns?(entity)
    parties.include?(entity)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :name, :password) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
    end

  public
  def ownership_check!(entity)
    security_violation unless current_user.owns?(entity)
  end

  def security_violation
    redirect_to root_path, notice: "Unauthorized."
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
  end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = current_user.parties.build(party_params)

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    Rsvp.where(party_id=@party.id).destroy_all    
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Party was successfully destroyed (yes, sounds very dramatic)' }      
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_party
      @party = Party.find(params[:id])
      ownership_check!(@party)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
      params.require(:party).permit(:description, :title)
    end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :set_rsvp, only: [:show, :edit, :update, :destroy]
   def create
    @rsvp = current_user.rsvps.build(rsvp_params)

    respond_to do |format|
      if @rsvp.save
        format.html { redirect_to @rsvp, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @rsvp }
      else
        format.html { render :new }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end
   def update
    respond_to do |format|
      if @rsvp.update(rsvp_params)
        format.html { redirect_to @rsvp, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @rsvp }
      else
        format.html { render :edit }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end
  def index
    @rsvp = Rsvp.all
  end
  def new
    @rsvp = Rsvp.new
  end
  def set_rsvp
    @rsvp = Rsvp.find(params[:id])
      ownership_check!(@rsvp)
    end
  
  def yes
    @rsvp = execute(update rsvp set going = true where party_id = #{:party_id} and user = #{this.user_id})
    end
  def no
    @rsvp = execute('update rsvp set going = false where party_id = #{:party_id} and user =  #{this.user_id} ')
end
    
    def destroy
    @rsvp.destroy
    Rsvp.where(party_id=@party.id).destroy_all    
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Reservation was successfully destroyed)' }      
      format.json { head :no_content }
    end
  end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end
  def dashboard
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Partylstr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to 'Party List', root_path %> |
  <%# user is logged in, show log out link %>
  <% if current_user.present? %>
    <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
  <%# user is not logged in, show signup and login links %>
  <% else %>
    <%= link_to 'Sign In', new_user_session_path %> |
    <%= link_to 'Register Now!', new_user_registration_path %>
  <% end %>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<h1>Listing parties</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parties.each do |party| %>
      <tr>
        <td><%= party.description %></td>
        <td><%= party.title %></td>
        <td><%= link_to 'Show', party %></td>
        <td><%= link_to 'Edit', edit_party_path(party) %></td>
        <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Party', new_party_path %>

app/views/parties/new.html.erb
<h1>New party</h1>

<%= render 'form' %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @party.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @party.title %>
</p>

<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>